### ISSUE TITLE
Pip subprocess error when running the project

### ISSUE THREAD

**Issue by alejandrobalderas** [udacity/nd0821-c2-build-model-workflow-starter#1]
I am getting the following error:

ERROR: Command errored out with exit status 128: git clone -q https://github.com/udacity/nd0821-c2-build-model-workflow.git

Running `mlflow run . -P wandb_api_key=${WANDB_API_KEY}` I am getting an error with pip failing to install a package. More specifically when trying to clone https://github.com/udacity/nd0821-c2-build-model-workflow.git. This comes from the components/get_data/conda.yml file. This repo does not exist.

We try to install a package with git under this URL:  git+https://github.com/udacity/nd0821-c2-build-model-workflow.git#egg=wandb-utils&subdirectory=project/solution/components

**Comment by alejandrobalderas** [comment]
I found a workaround by doing the following:

in config.yml
```
- components_repository: "https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#components"
+ components_repository: components
```
in main.py
```
+ root_path = hydra.utils.get_original_cwd()
  if "download" in active_steps:
              # Download file and load in W&B
              _ = mlflow.run(
->                os.path.join(root_path,config['main']['components_repository'],"get_data"),
               ....
```
in components/get_data/conda.yml
```
- git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=project/solution/components
+ -e ..
```
This installs the wandb_utils module locally instead of trying to get it from Github. The repository where this is being fetched does not exist and it throws an error.

**Comment by giacomov** [comment]
Yes, this is because when the code was moved from the private repo in which it was developed to here, these links were not updated. Let me fix these and make a PR.

**Comment by giacomov** [comment]
This is fixed as well. I tested all the steps of the instructions myself, you should be good to go now.
