### ISSUE TITLE
Download step not doing anything

### ISSUE THREAD

**Issue by alejandrobalderas** [udacity/nd0821-c2-build-model-workflow-starter#2]
After getting my environment running I am getting the following error:

ValueError: Path is not a file: data/sample1.csv

Looking at the run.py file inside of components/get_data I believe that a part of the code is missing. I see only the comments 

```
# We stream the file so that it can be downloaded even if it is bigger
# than the available memory
```

and then it directly tries to log an artifact.

There is no downloading or fetching of data and there is no sample1.csv in the repository.

What I expected:
See something like in exercise_14

```
# Download the file streaming and write to open temp file
with requests.get(args.file_url, stream=True) as r:
    for chunk in r.iter_content(chunk_size=8192):
        fp.write(chunk)

# Make sure the file has been written to disk before uploading
# to W&B
fp.flush()
```

**Comment by giacomov** [comment]
It is actually the comment that is out of date :-)

The data file is within the component itself, in the `data` directory.

I will remove the misleading comment about streaming.

**Comment by alejandrobalderas** [comment]
@giacomov thanks. One thing that is worth noting is that this repo does not have a `data` directory. Looking at issue #1 I am assuming that the private repo has the `data` directory but you will still have to push the data here 😄

**Comment by giacomov** [comment]
Good catch! I don't know how this repo was created, at the moment I don't have write permission to it so I can't fix anything. I'm working on obtaining that. Let me know if you find other problems!

**Comment by MernaHesham** [comment]
Hello @giacomov 

any updates on the data directory? I'm facing the same problem. I can't download the data.

**Comment by giacomov** [comment]
Hi!
Yes, I obtained write permission, i am going to fix this later today. Thanks!

**Comment by giacomov** [comment]
@MernaHesham @alejandrobalderas the problem is fixed, you should be able to continue now.

I also implemented several other comments and fixes, so make sure to restart from the top of the instructions. Things should be easier now.

**Comment by giacomov** [comment]
Please open other issues if you encounter other problems. Thanks!
